logging:
  config: ${LOG_CONFIG_PATH:}
  logdir: ${LOG_DIR:/logs}
  console-level: debug
  file-level: trace
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS}[%5p] --- [%-24t] [%-50C{50}][%-6L]: %m%n"
  level:
    root: info
    person.pluto: ${LOG_LEVEL:trace}
spring:
  application:
    name: natcross-boot-client
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: ${RESTART_ENABLED:true}

natcross:
  httpServer: ${NATCROSS_HTTP_SERVER:http://127.0.0.1:10080}
  httpProjectSign: ${NATCROSS_HTTP_SIGN_KEY:serverSignKey}
  clientServerIp: ${NATCROSS_CLIENT_SERVER_IP:127.0.0.1}
  clientServerPort: ${NATCROSS_CLIENT_SERVER_PORT:10010}
  aeskey: ${NATCROSS_AES_KEY:0PMudFSqJ9WsQrTC60sva9sJAV4PF5iOBjKZW17NeF4=}
  tokenKey: ${NATCROSS_TOKEN_KEY:tokenKey}
